version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: full_cycle
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql      
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  nodejs:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
    command:  bash -c "npm install && npm start"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: full_cycle
    depends_on:
      - mysql    


